//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSkassa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EVENTS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EVENTS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSkassa.EVENTS", typeof(EVENTS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Невозможно получить серийный номер.
        /// </summary>
        internal static string CANNOT_GET_SERIAL_NUMBER {
            get {
                return ResourceManager.GetString("CANNOT_GET_SERIAL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Не удалось получить настройки.
        /// </summary>
        internal static string CANNOT_GET_SETTINGS {
            get {
                return ResourceManager.GetString("CANNOT_GET_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Не удалось открыть порт.
        /// </summary>
        internal static string CANNOT_OPEN_PORT {
            get {
                return ResourceManager.GetString("CANNOT_OPEN_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Ошибка записи в порт.
        /// </summary>
        internal static string CANNOT_WRITE_PORT {
            get {
                return ResourceManager.GetString("CANNOT_WRITE_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Ошибка выполнения.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Ошибка получения субкоманды ККМ.
        /// </summary>
        internal static string ERROR__GETTING_SUBCOMMAND {
            get {
                return ResourceManager.GetString("ERROR__GETTING_SUBCOMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Не пришел ответ от ККМ или пустой ответ в запросе.
        /// </summary>
        internal static string ERROR_EMPTY_ANSWER {
            get {
                return ResourceManager.GetString("ERROR_EMPTY_ANSWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Ошибка заполнения запроса к ККМ.
        /// </summary>
        internal static string ERROR_FILLING_QUERY {
            get {
                return ResourceManager.GetString("ERROR_FILLING_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Ошибка получения статуса ККМ.
        /// </summary>
        internal static string ERROR_GET_STATUS {
            get {
                return ResourceManager.GetString("ERROR_GET_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Ошибка в ответе от ККМ.
        /// </summary>
        internal static string ERROR_IN_ANSWER_FROM_KKM {
            get {
                return ResourceManager.GetString("ERROR_IN_ANSWER_FROM_KKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Ошибка в структуре шаблона запросов к ККМ.
        /// </summary>
        internal static string ERROR_IN_QUERY_TEMPLATE {
            get {
                return ResourceManager.GetString("ERROR_IN_QUERY_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Заданное число слишком велико для ККМ.
        /// </summary>
        internal static string ERROR_NUMBER_IS_TOO_LONG {
            get {
                return ResourceManager.GetString("ERROR_NUMBER_IS_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Файл не найден.
        /// </summary>
        internal static string FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Повторяющееся значение КлючЗначение в файле чека.
        /// </summary>
        internal static string KEYVALUE_REPEAT {
            get {
                return ResourceManager.GetString("KEYVALUE_REPEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициализация ККМ.
        /// </summary>
        internal static string KKM_INIT {
            get {
                return ResourceManager.GetString("KKM_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Нет ответа от ККМ.
        /// </summary>
        internal static string NO_ANSWER_KKM {
            get {
                return ResourceManager.GetString("NO_ANSWER_KKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Не найден шаблон настроек для кассы.
        /// </summary>
        internal static string NO_QUERIES_TEMPLATE {
            get {
                return ResourceManager.GetString("NO_QUERIES_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Не указаны параметры работы программы.
        /// </summary>
        internal static string PARAMETERS_NOT_FOUND {
            get {
                return ResourceManager.GetString("PARAMETERS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Внутренняя ошибка! Не найден объект подключения СОМ порта.
        /// </summary>
        internal static string RS_OBJ_IS_NULL {
            get {
                return ResourceManager.GetString("RS_OBJ_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Не найдены настройки программы &quot;tskassa.cfg&quot;.
        /// </summary>
        internal static string SETTINGS_NOT_FOUND {
            get {
                return ResourceManager.GetString("SETTINGS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки успешно прочтены.
        /// </summary>
        internal static string SETTINGS_READED {
            get {
                return ResourceManager.GetString("SETTINGS_READED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Касса не поддерживается.
        /// </summary>
        internal static string WRONG_KKM {
            get {
                return ResourceManager.GetString("WRONG_KKM", resourceCulture);
            }
        }
    }
}
